# Generated by Django 5.1.2 on 2024-10-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Db',
            new_name='Food_Db',
        ),
    ]
