# Generated by Django 5.1.2 on 2024-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoApp', '0002_rename_category_db_food_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('Food_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Food_Description', models.TextField(blank=True, max_length=500, null=True)),
                ('Food_Imagea', models.ImageField(blank=True, null=True, upload_to='Food_Items')),
                ('Food_Imageb', models.ImageField(blank=True, null=True, upload_to='Food_Items')),
                ('Food_Imagec', models.ImageField(blank=True, null=True, upload_to='Food_Items')),
            ],
        ),
    ]
