# Generated by Django 5.1.2 on 2024-10-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
