# Generated by Django 5.1.2 on 2024-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile_Number', models.IntegerField(blank=True, null=True)),
                ('Pass_word', models.CharField(blank=True, max_length=15, null=True)),
                ('Re_pass', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
